### ISSUE TITLE
Script to mine repositories for Git secrets

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#933] opened 2021-04-02 03:31 UTC
# Description

Sometimes we inadvertently commit secrets in our GitHub repository that otherwise should not have been there. This creates a lot of risk, especially when we expose proprietary information, like our API Keys, AWS configs and more. To prevent this, we can scan the repositories for these secrets and warn, if we find any. This script should take up GitHub repositories and scan them for any secrets if found. 

Ideally this can serve as a CLI tool that can be used in the following ways: 

- Scanning personal repositories (Public Repositories only) 
- Scanning trending repositories (Fetch using any unofficial GitHub API) 
- Scanning repositories from a CSV File (Single-Column with the GitHub Repo URL) 

You can use your own customization to find how the script can serve the purpose

## Language

- [X] Go
- [X] Javascript
- [X] Python

**Comment by rahulraikwar00** [comment] 2021-04-11 20:28
@vybhav72954 I think github it self does this right?...if we accidentally pushed any type of Credentials..it informs us by email but it is still limited for GitHub credentials.
I think this is something we can work on
What do you think? Have any idea or suggestion?

**Comment by vybhav72954** [comment] 2021-04-11 21:10
> @vybhav72954 I think github it self does this right?...if we accidentally pushed any type of Credentials..it informs us by email but it is still limited for GitHub credentials.
> I think this is something we can work on
> What do you think? Have any idea or suggestion?

Yup GitHub Actively looks for secrets. But only for the Password and the email if it's set to be invisible,
What Harsh wants is to scan the Repo for API keys and other Configs as well.

**Comment by vybhav72954** [comment] 2021-04-11 21:14
Actually, this issue is a duplicate of #434

I worked in this as well, the max I was able to achieve was look for `.env` files. I was able to achieve this, but there are a few problems with that approach.

- `.gitignore` usually ignores `.env`.
- Those who know about `.env` are aware enough not to commit it in the first place.

So well my attempt was mostly useless and that's why I never pushed it. In case you have a better approach, we can discuss it here as well.

**Comment by HarshCasper** [comment] 2021-04-12 05:08
Here is something that we can use as an inspiration: 

- [Git Secrets](https://github.com/awslabs/git-secrets)
- [Gittyleaks](https://github.com/kootenpv/gittyleaks)
- [Python Git Scripts](https://pypi.org/project/python-git-secrets/#:~:text=A%20pure%20Python%20library%20providing,to%20the%20world%20via%20Github.) 

Your approach is also good @vybhav72954. Perhaps that solution can serve as the v1 of the script and can be further developed on top of it.

**Closed** 2021-10-03 09:28 UTC
Labels: enhancement, Up-For-Grab, Python, Javascript, Golang, GSSOC21
