### ISSUE TITLE
Create a Script to summarize Text

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#539] opened 2020-11-08 05:01 UTC
# Description

Create a Script to summarize Text. You can take a look at some SOTA Techniques to achieve this along with wrappers that make it really easy to summarize the Text. You can also try out your own algorithm for Text Summarization and to make it lightweight and-efficient at the same time.

## Language

- [X] Python

## Type of issue

_Please delete options that are not relevant._

- [X] Feature

**Comment by DevChoganwala** [comment] 2020-11-08 18:23
@HarshCasper I would like to work on this issue in python

**Comment by ag-hcoder** [comment] 2020-11-30 06:03
@DevChoganwala are you still working on it? If not, @HarshCasper could you please assign this to me

**Comment by HarshCasper** [comment] 2020-12-01 06:21
Hello @ag-hcoder 

Assigned it to you. Let me know if you are working on it as part of NJACK Winter of Code, so that I can put apt labels.

**Comment by ag-hcoder** [comment] 2020-12-01 07:36
Yes, I'm working as a part of NJACK

**Comment by dijodaiju7** [comment] 2020-12-08 06:07
I would like to work on this issue, can you please assign it to me? @HarshCasper

**Comment by HarshCasper** [comment] 2020-12-29 12:38
Are you still working on it @ag-hcoder 

If not, I will assign this Issue to someone else.

**Comment by vybhav72954** [comment] 2021-01-02 09:07
Is this still open @HarshCasper

**Comment by vybhav72954** [comment] 2021-01-16 08:10
@HarshCasper You mentioned SOTA, i am assuming you want something like `LSTM` or `R-NN`

If I use `NLTK` because natural language is my place of interest, would it be fine? I can definitely guarantee that it would be more efficient than any Short term memory classifier, but the weight would be an issue.

Alternatively, I can make both of the scripts, and show the differences, I think that it would be a great learning experience for me as well, exploring corner use cases would be interesting as hell.

But the problem Is that this is marked as `easy` so I assume you don't need all of that here, in order to keep it really light-weight and efficient, I can simply use libraries that are somewhat meant for this purpose. A combination of **Word Normalizer**, **Word Vector** and **Word  Parser** will do the trick.

So these are the options I can think of, guide me here.

**Comment by HarshCasper** [comment] 2021-01-16 11:45
> @HarshCasper You mentioned SOTA, i am assuming you want something like `LSTM` or `R-NN`
> 
> If I use `NLTK` because natural language is my place of interest, would it be fine? I can definitely guarantee that it would be more efficient than any Short term memory classifier, but the weight would be an issue.
> 
> Alternatively, I can make both of the scripts, and show the differences, I think that it would be a great learning experience for me as well, exploring corner use cases would be interesting as hell.
> 
> But the problem Is that this is marked as `easy` so I assume you don't need all of that here, in order to keep it really light-weight and efficient, I can simply use libraries that are somewhat meant for this purpose. A combination of **Word Normalizer**, **Word Vector** and **Word Parser** will do the trick.
> 
> So these are the options I can think of, guide me here.

Yeah. I was essentially exploring some new Modules that make Text Summarization as simple as a module import. You can definitely go ahead with the NLTK solution 👍

**Comment by vybhav72954** [comment] 2021-01-16 11:51
> But the problem Is that this is marked as `easy` so I assume you don't need all of that here, in order to keep it really light-weight and efficient, I can simply use libraries that are somewhat meant for this purpose. A combination of **Word Normalizer**, **Word Vector** and **Word Parser** will do the trick.

So basically this if am not wrong?

**Comment by HarshCasper** [comment] 2021-01-23 04:03
> > But the problem Is that this is marked as `easy` so I assume you don't need all of that here, in order to keep it really light-weight and efficient, I can simply use libraries that are somewhat meant for this purpose. A combination of **Word Normalizer**, **Word Vector** and **Word Parser** will do the trick.
> 
> So basically this if am not wrong?

Yeah

**Comment by vybhav72954** [comment] 2021-01-24 15:46
@HarshCasper This is taking time because for some reason I can't install `neologdn` package, I don't know why its happening either :|

**Closed** 2021-02-10 06:21 UTC
Labels: Easy, NJACK'20, Python, Up-For-Grab, enhancement

**Comment by vybhav72954** [comment] 2021-02-10 06:26
@HarshCasper Assign proper labels if possible
