### ISSUE TITLE
Face Recognition and Facial Expression Recognition in python

### ISSUE THREAD

**Issue by Debashish-hub** [HarshCasper/Rotten-Scripts#858] opened 2021-03-16 19:53 UTC
**This template is strictly for requesting New Scripts, if you want a new feature (automating this Repo,**
**a change in structure) in the Repo,** 
**or you want to report a Bug. There are other templates which you should follow**

# Description
I would like to create a script of Face recognition which can detect the face of a person and show his/her name from the database and another script that will recognize the facial expression of a person at real time.

## Language

- [ ] Bash
- [ ] Go
- [ ] Javascript
- [ ] Powershell
- [x] Python
- [ ] Other (Please specify)

## Checklist:

- **Details on the Script**

I will be working as a GSSOC'21 participant, so I will need a label of gssoc. It would be great if I get assigned on this issue @HarshCasper 

| name            | about                                                  | labels  | assignees                                                      |
| --------------- | ------------------------------------------------------ | ------- | -------------------------------------------------------------- |
| Face Recognition and Facial Expression Recognition | I would like to create a script of Face recognition which can detect the face of a person and show his/her name from the database and another script that will recognize the facial expression of a person at real time. | gssoc | @Debashish-hub |

For inspiration, see [this](https://github.com/anubhavshrimal/Face-Recognition).

**Comment by vybhav72954** [comment] 2021-03-17 10:44
This looks good to me

**Comment by vybhav72954** [comment] 2021-03-18 13:03
@Debashish-hub The issue is still assigned to you. Looking forward to a new PR.

**Comment by vybhav72954** [comment] 2021-03-19 07:48
Are you working on this? @Debashish-hub

**Comment by Debashish-hub** [comment] 2021-03-19 07:51
Yes

**Closed** 2021-04-01 18:37 UTC
Labels: Assigned, GSSOC21, Level3, Python, enhancement
