### ISSUE TITLE
Google Drive Content Downloader

### ISSUE THREAD

**Issue by srimani-programmer** [HarshCasper/Rotten-Scripts#318] opened 2020-09-01 13:12 UTC
# Description
Develop a script that should download the content that is stored in the google drive. The script should download the entire folder or a particular file based on the given link. The script should use multithreading to download the large files very easily. 

## Language

- [x] Go
- [x] Javascript
- [x] Python

## Type of issue

- [x] Feature

**Comment by akshaysonawaneS** [comment] 2020-09-02 03:07
I will like to work on this.

**Comment by srimani-programmer** [comment] 2020-09-02 04:08
@akshaysonawaneS issue is assigned to you.!

**Comment by vybhav72954** [comment] 2020-10-16 15:52
@HarshCasper @srimani-programmer Is this still open in Python?

**Comment by HarshCasper** [comment] 2020-10-29 07:27
@xenowits Kindly let me know if you are ready to take it up in Golang. I will assign it to you. 

@vybhav72954 The Issue is open in Python, but you can take it up once the rest Issue assigned to you are resolved.

**Comment by sujal111** [comment] 2020-12-05 18:29
Please allow me to work this issue

**Comment by HarshCasper** [comment] 2020-12-17 15:35
Hello @sujal111 

Please go ahead in working on this!

**Comment by HarshCasper** [comment] 2020-12-29 12:24
Are you working on this @sujal111 ? 

If not, I will assign this to someone else.

**Comment by vybhav72954** [comment] 2021-01-02 11:19
@HarshCasper Is this open?

**Closed** 2021-10-03 09:19 UTC
Labels: good first issue, Up-For-Grab, Hard, Assigned, Python, Javascript, Golang
