### ISSUE TITLE
Send Connection Requests on LinkedIn

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts#164] opened 2020-08-03 03:15 UTC
# Description

Create a Script that can send Connection Requests on LinkedIn with a personalized note as given by the User.

## Language

- [X] Javascript
- [X] Python
- [X] Golang

## Type of issue

*Please delete options that are not relevant.*

- [X] Feature

## Checklist:

- **For Feature**

|name|about|labels|assignees|
|----|-----|------|---------|
|Send Connection Request|Script to send personalized Connection Requests on LinkedIn with a note|SLoP, Python, JS, Golang|`Open for SLoP Participants`|

**Comment by mohitacecode** [comment] 2020-08-06 12:31
Please assign this issue to me

**Comment by HarshCasper** [comment] 2020-08-10 02:08
I have assigned this to you @mohitacecode

**Comment by SANKET7738** [comment] 2020-09-02 14:24
If open, I would like to work on this.

**Comment by vybhav72954** [comment] 2020-10-16 15:54
@HarshCasper Is this still open in python?

**Comment by HarshCasper** [comment] 2020-10-29 07:23
I am assigning this to you @vybhav72954

**Comment by vybhav72954** [comment] 2020-10-31 10:48
@HarshCasper This issue is solved in `Python`, [here](https://github.com/HarshCasper/Rotten-Scripts/tree/master/Python/Automate-LinkedIN)

I'll solve this using JS.

This might take some time as JS is not my forte.

**Comment by HarshCasper** [comment] 2020-12-01 04:17
Hello @vybhav72954 

Let me know if you are still working on the same. Otherwise, I will open the Issue for NJACK Participants

**Comment by vybhav72954** [comment] 2020-12-01 07:19
The issue is solved using python. And am unable to solve it using JS. I will unassign myself. Sorry i kept you waiting

**Closed** 2020-12-01 08:05 UTC
Labels: Golang, Javascript, Python, SLoP
